### ISSUE TITLE
Hangs on visiting the Shore

### ISSUE THREAD

**Issue by paronomasiac** [Malurth/Auto-2-day-HCCS#17]
I've tried twice now, and both times the script attempted to vacation at the shore when I had fewer than 3 adventures remaining. When this happens, the script endlessly hits the shore choice.

**Comment by Malurth** [comment]
Yeah, it does that. But if you had that low of an adv count by that time, you were pretty screwed anyway.

**Comment by paronomasiac** [comment]
So the basic necessities aren't then? Because I have all those, and a small smattering of other IOTMs

**Comment by Malurth** [comment]
The basic prerequisites are exactly those that are needed to actually run the script. You'll need a lot more to actually be able to use it _effectively_. I recommend poring over the readme more closely, as it describes in pretty good detail what you'll need to make good use of the script.

**Comment by paronomasiac** [comment]
The script doesn't automatically stop, yes. But it doesn't function as an automated ascension script.

**Comment by Malurth** [comment]
It functions quite well as an automated ascension script if you have the goods to use it properly. It's called 2 day HCCS for a reason; if it is failing to meet the pace required for 2 day, it won't work.

**Comment by RESPRiT** [comment]
Do you have all the skills that are required as well? There's not set in stone combination (at least none that I know of), but you need to have a decent amount of the recommended skills for the script to work. The hanging could be fixed, sure, but this script was written with the assumption that the user running it would actually be successful. If you don't have adventures left at the Shore, your run is certainly not going to be successful.

**Comment by paronomasiac** [comment]
I have 100% of the "basic prerequisites," a few of the other mentioned IotM's, and a handful of the skills listed in "anything else I should know." My primary complaint is that, while the "basics" keep the script from automatically aborting, they do not result in the script automating an ascension. I don't particularly care about the script hitting a 2-day ascension. I care about the script automating an ascension, and it fails at that.

**Comment by RESPRiT** [comment]
I don't know what to tell you, "2-day" is in the title, try using CheeseCookie's script instead or one of the 3-day CS scripts.

**Comment by paronomasiac** [comment]
How about a list of the actual minimum basic requirements to run this as an automated ascension script?

**Comment by RESPRiT** [comment]
I don't think you understand what "basic requirements" means. The basics are what are required to run the script. There is no way to recommend an exact list of items and skills needed for the script to be successful, as there are many different combinations that work. If you are still confused, try to understand this: running the script and the script being successful are not the same thing. I'm sorry the script is not working for you, but your issue is not the script's fault.
