### ISSUE TITLE
lack of xi

### ISSUE THREAD

**Issue by darkbob9** [Malurth/Auto-2-day-HCCS#18]
If you don't have the xiblaxian stuff, the script fails on day 2 when you try to do this line:

cli_execute("eudora xi"); // switch back to Xi

When it failed there, I had to go in and comment out a bunch of stuff just to get it to finish the run.  Luckily I still managed to get a 2-day run.  :)

**Comment by Malurth** [comment]
Just pushed an untested fix for this

...about 11 months late, sorry
