### ISSUE TITLE
Hangs on revisit to the Meatsmith

### ISSUE THREAD

**Issue by MrHrulgin** [Malurth/Auto-2-day-HCCS#2]
For some reason the script tried to revisit the meatsmith, and hung because it didn't know how to exit except by accepting the quest. I added the line:

visit_url("choice.php?pwd&whichchoice=1059&option=3&choiceform1=Not+yet.+I%27ll+keep+looking."

and it got past that point. I'd try to set up a merge request or whatever it's called, but I don't know what I'm doing, and don't want to mess it up.

**Comment by Malurth** [comment]
Well, it shouldn't ever try to go to that choice anyway, as far as I know...where did you insert that line?

**Comment by MrHrulgin** [comment]
It hung initially at the attempt to set the radio to 11, and then running it a second time got me 

"Running HCCS Day 1...
Selling jewels...
Encounter: Helping Make Ends Meat
Encounter: Helping Make Ends Meat
You are currently in a choice."

And then it hung again. I got it to get past that by adding that line to the bottom of the logic for dealing with the skeleton store mission:
void unlockSkeletonStore() {
    visit_url("shop.php?whichshop=meatsmith&action=talk");
    visit_url("choice.php?pwd&whichchoice=1059&option=1&choiceform1=Sure%2C+I%27ll+go+check+it+out.");

**Comment by Malurth** [comment]
Oh, I see. I forgot that's how you unlock the Skeleton Store. So if you tried running it again after it failed for some reason it would go to the same choice adventure and the option to accept the quest would be gone, so it would hang. I'll insert that fix, thanks.
