### ISSUE TITLE
No detection of existing buffs or buff items when trying to recover from a fault

### ISSUE THREAD

**Issue by MrHrulgin** [Malurth/Auto-2-day-HCCS#3]
I attempted to run the script today and ran into an unrelated bug with the maximizer (trying to free pull actual reality goggles to max spell damage when they're too old for the path), but when I tried to run it again, it crafted an additional 3 cordials of concentration as opposed to using one of the other two I had from the first time, and buffed me again despite still having the buff from the first time.

**Comment by Malurth** [comment]
Okay a lot of the times it does so it's not really a general case problem but yeah I'll throw in a check to see if you already have the cordial

**Comment by MrHrulgin** [comment]
Thank you. I appreciate that you're working on this thing, and I definitely want to help make it happen, as I can.
