### ISSUE TITLE
powerlevel() in Video Game level 1 will clear it before 15 turns are up.

### ISSUE THREAD

**Issue by xxx** [Malurth/Auto-2-day-HCCS#5]
Just ran into this (though not sure why my charters were not recognized), but yeah. It will clear the area before the 15 turns are up and stop the script.

**Comment by Malurth** [comment]
Thanks, I'll fix this. Also mafia might not know you have those charters (happens sometimes); you should open your KoLmafia account properties file (under "settings\[your_username]_prefs.txt") and search for the variables spookyAirportAlways, hotAirportAlways, etc; if they are set to "false" when in reality you actually have them, just change them to "true" and save.

**Comment by xxx** [comment]
Ah, thanks for that. Yeah, my prefs file was saying they were all false, though _<X>AirportToday was true on all of them. Let's just blame Mafia for that one.

**Comment by Malurth** [comment]
Should be fixed now.

**Comment by Malurth** [comment]
Or not.

**Comment by Malurth** [comment]
Okay should be fixed this time.
