### ISSUE TITLE
in powerlevel(), shouldn't Galloping Grill be checked for and used before Hovering Sombrero?

### ISSUE THREAD

**Issue by xxx** [Malurth/Auto-2-day-HCCS#7]
Is there a reason to not use the Grill over the Sombrero if you have one?

**Comment by Malurth** [comment]
the reason is because I am a grade-A doofus and thought the Grill was a volleyball, not a sombrero.

Should be fixed soon.

**Comment by Malurth** [comment]
Fixed by recent pull from soolar
